# Generated by Django 4.0.6 on 2022-07-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0002_course_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='sampleanswer',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
